blank_issues_enabled: false

issue_templates:
  - name: "ğŸ› Bug report"
    description: Report something that isn't working as expected
    labels: ["bug"]
    assignees: ["cosminneamtiu02"]
    file: bug_report.yml

  - name: "âœ¨ Feature request"
    description: Suggest an idea or improvement
    labels: ["feature"]
    assignees: ["cosminneamtiu02"]
    file: feature_request.yml
